services:
  aws-cli:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: aos-sentiment-cli:latest
    container_name: aos-sentiment-container
    volumes:
      - ~/.aws:/root/.aws:rw
      - ~/.aws/sso/cache:/root/.aws/sso/cache:rw
    environment:
      - AWS_PROFILE=xmas
      - AWS_DEFAULT_REGION=us-east-1
    stdin_open: true
    tty: true





