
services:
  sam:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: sam-python3.12:latest
    container_name: aos-sentiment-container
    working_dir: /app/cloudformation
    command: /bin/bash -c "while true; do sleep 3600; done"
    volumes:
    #  - .:/app/cloudformation
      - ~/.aws:/root/.aws:rw
     # - ${HOME}/.aws/sso/cache:/root/.aws/sso/cache:ro
    environment:
      - AWS_PROFILE=xmas
      - AWS_DEFAULT_REGION=us-east-1
      - SAM_CLI_TELEMETRY=0
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "3000:3000"  # For SAM local API testing
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


